### ISSUE TITLE
Reference `.env` file instead of hardcoding Key values in code.

### ISSUE THREAD

**Issue by shivanshu-semwal** [kanakmi/Detective-Discord#2]
https://github.com/kanakmi/Detective-Discord/blob/8b8118f8476d2052d973e88bc104c0a8f4b19300/bot.py#L12

I suggest we should load these values form `.env` file which is the usual method, and a security measure, and not put senstive information in code.

**Comment by kanakmi** [comment]
Done in https://github.com/kanakmi/Detective-Discord/commit/be38acfc858c2f7847e56089ce8c2c1d7fe97aa0
