### ISSUE TITLE
Improve the Readme file

### ISSUE THREAD

**Issue by kanakmi** [kanakmi/Detective-Discord#4]
Improve the readme file and fix any gramatical errors that you find.

**Comment by AdarshCoder397** [comment]
Hey @kanakmi , I can work on this!!

**Comment by kanakmi** [comment]
Sure @AdarshCoder397 I’m assigning this to you.

**Comment by AdarshCoder397** [comment]
Thanks @kanakmi !

**Comment by AdarshCoder397** [comment]
Hey @kanakmi , I have made a PR kindly review and merge it!
