### ISSUE TITLE
Try to install and run locally on your machine

### ISSUE THREAD

**Issue by kanakmi** [kanakmi/Detective-Discord#5]
Try to run the bot locally on your machine and if you find any missing steps in README.md #74, update them accordingly.

**Comment by kaustav202** [comment]
I want to take it up @kanakmi

**Comment by kanakmi** [comment]
Hey @kaustav202 please first complete the issue that has already been assigned to you before taking up another one. Also I would suggest leave this one for the people contributing to this repo for the first time.

**Comment by JurassikLizard** [comment]
Could this be assigned to me?

**Comment by kanakmi** [comment]
Sure, go ahead @JurassikLizard. I am assigning this to you.
