### ISSUE TITLE
Improve the Contributing.md file

### ISSUE THREAD

**Issue by kanakmi** [kanakmi/Detective-Discord#6]
Improve the [Contributing.md](https://github.com/kanakmi/Detective-Discord/blob/Version-2.0/CONTRIBUTING.md) file and fix any gramatical errors that you find.

**Comment by kaustav202** [comment]
can I work on this @kanakmi

**Comment by kanakmi** [comment]
Sure @kaustav202 go ahead 👍🏻

**Comment by AdarshCoder397** [comment]
Hey @kanakmi , I can do this!

**Comment by kanakmi** [comment]
Hey @AdarshCoder397, I have already assigned this to Kaustav. Would you like to pick one of the other open issues?
